[package]
name = "zenith_renderer"
edition.workspace = true
license.workspace = true
authors.workspace = true
version.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
glam = { version = "0.33.3", default-features = false, features = [
    "std",
    "float-types",
    "fast-math",
    "bytemuck",
    "serde",
] }
winit = "0.30.13"
wgpu = { version = "30.0.1", features = ["webgl"] }
zenith_error = { version = "0.1.0", path = "../zenith_error" }
zenith_log = { version = "0.1.0", path = "../zenith_log" }
serde = "1.0.229"
bevy_ecs = { version = "0.19", features = [
    "multi_threaded",
    "trace",
    "serialize",
] }
bytemuck = "1.25.2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-time = "1.1.0"

[lints]
workspace = true
