unstable_features = true
max_width = 120
hard_tabs = true
newline_style = "Unix"
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
fn_single_line = false
condense_wildcard_suffixes = true
wrap_comments = true
format_code_in_doc_comments = true
