[package]
name = "zenith_editor"
edition.workspace = true
license.workspace = true
authors.workspace = true
version.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
dear-app = "0.18.0"
zenith_error = { version = "0.1.0", path = "../../crates/zenith_error" }
zenith_log = { version = "0.1.0", path = "../../crates/zenith_log" }
zenith_package = { version = "0.1.0", path = "../../crates/zenith_package" }

[lints]
workspace = true
