# bins/runtime/Cargo.toml
[package]
name = "ze_runtime"
edition.workspace = true
license.workspace = true
authors.workspace = true
version.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
ze_error = { version = "0.1.0", path = "../../crates/ze_error" }
ze_log = { version = "0.1.0", path = "../../crates/ze_log", features = [
    "profiling",
] }
ze_types = { version = "0.1.0", path = "../../crates/ze_types" }
ze_components = { version = "0.1.0", path = "../../crates/ze_components" }
tracing = "0.1.30"

ze_world = { version = "0.1.0", path = "../../crates/ze_world" }


[lints]
workspace = true
