# bins/runtime/Cargo.toml
[package]
name = "ze_runtime"
edition.workspace = true
license.workspace = true
authors.workspace = true
version.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
ze_error = { version = "0.1.0", path = "../../crates/ze_error" }
ze_log = { version = "0.1.0", path = "../../crates/ze_log", features = ["profiling"] }
tracing = "0.1"

[lints]
workspace = true
