[package]
name = "zenithpack_cli"
readme = "Readme.md"
edition.workspace = true
license.workspace = true
authors.workspace = true
version.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[[bin]]
name = "zenithpack"
path = "src/main.rs"

[dependencies]
zenithpack = { version = "0.1.0", path = "../../crates/zenithpack" }
