[package]
name = "ze_registry"
edition.workspace = true
license.workspace = true
authors.workspace = true
version.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
bevy_ecs = { version = "0.19", features = [
    "multi_threaded",
    "trace",
    "serialize",
] }
serde-saphyr = "1.0.1"
ze_types = { version = "0.1.0", path = "../ze_types" }
ze_entity_id = { version = "0.1.0", path = "../ze_entity_id" }
serde_json = "1.0.151" # for component types and their parsing by serde_saphyr
tracing = "0.1"

[lints]
workspace = true
