[package]
name = "zenith_theme"
edition.workspace = true
license.workspace = true
authors.workspace = true
version.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
csscolorparser = { version = "0.8.4", features = ["serde"] }
serde = "1.0.229"
zenith_error = { version = "0.1.0", path = "../zenith_error" }

[lints]
workspace = true
