[package]
name = "ze_types"
edition.workspace = true
license.workspace = true
authors.workspace = true
version.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
bevy_ecs = { version = "0.19", features = [
    "multi_threaded",
    "trace",
    "serialize",
] }
ze_entity_id = { version = "0.1.0", path = "../ze_entity_id" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
glam = { version = "0.33.3", default-features = false, features = [
    "std",
    "float-types",
    "fast-math",
    "bytemuck",
    "serde",
] }
semver = { version = "1.0.28", features = ["serde"] }
serde-saphyr = "1.0.1"

[lints]
workspace = true
