[package]
name = "ze_audio"
edition.workspace = true
license.workspace = true
authors.workspace = true
version.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
kira = "0.12"
ze_core = { path = "../ze_core" }
ze_ecs = { path = "../ze_ecs" }
ze_assets = { path = "../ze_assets" }
ze_scripting_cs = { path = "../ze_scripting_cs" }
ze_log = { path = "../ze_log" }
