[book]
title = "ZenithEngine Documentation"
description = "Documentation and API reference for Zenith Engine"
authors = ["Gleb Petrikov"]
language = "en"
src = "src"

[rust]
edition = "2024"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
site-url = "/"
git-repository-url = "https://github.com/glpetrikov/ZenithEngine"
git-repository-icon = "fab-github"
cname = ""

[output.html.fold]
enable = true
level = 1

[output.html.playground]
editable = false
copyable = true
line-numbers = false
copy-js = false
runnable = false

[output.html.search]
limit-results = 30
use-boolean-and = true
expand = true
heading-split-level = 2
